[package]
name = "infi-erp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
tracing = "0.1.4"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
axum = "0.7.4"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
askama = { version = "0.12.1", features = ["serde", "serde-json"] }
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio", "macros"] }
tower-http = { version = "0.5.1", features = ["normalize-path", "trace"] }
tower = "0.4.13"
