[package]
name = "infi-erp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
tokio = { version = "1", features = ["full"] }
poem = { version = "2" }
poem-openapi = { version = "4", features = ["rapidoc"] }
sqlx = { version = "0.7", features = [
  "postgres",
  "runtime-tokio",
  "tls-rustls",
  "macros",
] }
