application:
  udp_port: 24680
  udp_buffer_size: 10024
  http_port: 8080
  http_host: "127.0.0.1"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "postgrespw"
  database_name: "erp"
