version: "3"
services:
  api:
    image: dvalinn/infi-erp
    restart: always
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "24680:24680"
      - "24900:24900"
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
