version: "3"
services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    # NOTE: in production this should be uncommented
    # volumes:
    #   - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      #TODO: Add these variables as secrets
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    # NOTE: in production this should be uncommented
    # volumes:
    #   - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  api:
    image: dvalinn/infi-erp
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "24680:24680"
    depends_on:
      - postgres
# NOTE: in production this should be uncommented
# volumes:
#   postgres:
#   driver: local
#   pgadmin:
#   driver: local
