CREATE TABLE IF NOT EXISTS client_orders (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  ClientNameId VARCHAR NOT NULL,
  OrderNumber INT NOT NULL,
  WorkPiece VARCHAR NOT NULL,
  Quantity INT NOT NULL,
  DueDate INT NOT NULL,
  LatePen MONEY NOT NULL,
  EarlyPen MONEY NOT NULL
);
