CREATE TABLE IF NOT EXISTS client_orders (
  OrderNumber BIGINT NOT NULL PRIMARY KEY,
  ClientNameId VARCHAR NOT NULL,
  WorkPiece VARCHAR NOT NULL,
  Quantity INT NOT NULL,
  DueDate INT NOT NULL,
  LatePen MONEY NOT NULL,
  EarlyPen MONEY NOT NULL
);
